name: py310
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cudatoolkit=11.2.2=h7d7167e_13
  - cudnn=8.1.0.77=h3e0f4f4_0
  - debugpy=1.8.19=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - icu=78.1=h637d24d_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.1=hf5d6505_1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.3.0=hac47afa_454
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=1.23.5=py310h4a8f9c9_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py310h1637853_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=hc20f281_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pywin32=311=py310h282bd7d_1
  - pyzmq=27.1.0=py310h535538e_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.4=py310h29418f3_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h5bddc39_9
  - pip:
      - absl-py==2.3.1
      - aggdraw==1.3.19
      - astunparse==1.6.3
      - cachetools==6.2.4
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - gast==0.4.0
      - google-auth==2.45.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - greenlet==3.3.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - joblib==1.5.3
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - lxml==6.0.2
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - oauthlib==3.3.1
      - obspy==1.4.2
      - opt-einsum==3.4.0
      - pandas==2.3.3
      - patsy==1.0.2
      - pillow==12.1.0
      - protobuf==3.19.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.3.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sqlalchemy==1.4.54
      - statsmodels==0.14.6
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.3.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tzdata==2025.3
      - urllib3==2.6.2
      - visualkeras==0.2.0
      - werkzeug==3.1.4
      - wrapt==2.0.1
prefix: C:\Users\nicol\anaconda3\envs\py310
